name: '[PR] Tests pass and build is successful'

on:
    workflow_dispatch:
    pull_request:

jobs:
    check-pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: 'pnpm'
            - run: pnpm install --frozen-lockfile
            - run: pnpm test
            - run: pnpm build
